main:src/main.o src/IntVector.o
	gcc -Wall -o src/main.o src/IntVector.o main
	rm src/IntVector.o src/main.o

main.o:src/main.c src/IntVector.h
	gcc -c src/main.c

IntVector.o src/IntVector.c src/IntVector.h
	gcc -c src/IntVector.c